version: '3.8'

services:
  hytale:
    image: deinfreu/hytale-server:experimental
    container_name: hytale-server
    environment:
      SERVER_IP: "0.0.0.0"
      SERVER_PORT: "5520"
      PROD: "FALSE"
      DEBUG: "FALSE"
      TZ: "Europe/London"
    restart: unless-stopped
    labels:
      - 'portical.upnp.forward=published'
    ports:
      - "5520:5520/udp"
    volumes:
      - '/data/servers/hytale:/home/container'
      - '/data/servers/hytale/machine-id:/etc/machine-id:ro'
    tty: true
    stdin_open: true