version: '3.8'

services:
  hytale:
    image: deinfreu/hytale-server:experimental
    container_name: hytale-dan
    environment:
      SERVER_IP: "0.0.0.0"
      SERVER_PORT: "5521"
      PROD: "FALSE"
      DEBUG: "FALSE"
      TZ: "Europe/London"
    restart: unless-stopped
    labels:
      - 'portical.upnp.forward=published'
    ports:
      - "5521:5521/udp"
    volumes:
      - '/data/servers/hytale-dan:/home/container'
      - '/data/servers/hytale-dan/machine-id:/etc/machine-id:ro'
    tty: true
    stdin_open: true